name: quakes
region: ams
services:
- dockerfile_path: dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: logileifs/quakes
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: quakes
  routes:
  - path: /
  health_check:
    http_path: '/health/'