apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ .Values.app }}
          servicePort: 8000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.app }}
          servicePort: 8000
---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: http-redirect-ingressroute
#spec:
#  entryPoints:
#    - web
#  routes:
#    - match: Host(`localhost`) && PathPrefix(`/api`)
#      kind: Rule
#      services:
#        - name: {{ .Values.app }}
#          port: 8000
#      middlewares:
#        - name: {{ .Values.app }}-stripprefix
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: {{ .Values.app }}-stripprefix
#spec:
#  stripPrefix:
#    prefixes:
#      - /api
#---
# httpproxy.yaml
#apiVersion: projectcontour.io/v1
#kind: HTTPProxy
#metadata:
#  name: {{ .Values.app }}-ingress-cluster
#spec:
#  virtualhost:
#    fqdn: cluster
#  routes:
#    - conditions:
#      - prefix: /api
#      services:
#        - name: {{ .Values.app }}
#          port: 8000
#      pathRewritePolicy:
#        replacePrefix:
#        - replacement: /
#---
#apiVersion: projectcontour.io/v1
#kind: HTTPProxy
#metadata:
#  name: {{ .Values.app }}-ingress-localhost
#spec:
#  virtualhost:
#    fqdn: localhost
#  routes:
#    - conditions:
#      - prefix: /api
#      services:
#        - name: {{ .Values.app }}
#          port: 8000
#      pathRewritePolicy:
#        replacePrefix:
#        - replacement: /
