name: Preview on pull request
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry config virtualenvs.create false
      - run: poetry install  --without dev,test
      - uses: pulumi/actions@v3
        with:
          diff: true
          stack-name: dev
          command: preview
          comment-on-pr: true
          edit-pr-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
