metrics-server:
  enabled: False
vector:
  customConfig:
    sinks:
      better_stack_http_sink:
        auth:
          token: '4fdA9Yq65r2hKcrajt9P3hBE'
      better_stack_http_metrics_sink:
        auth:
          token: '4fdA9Yq65r2hKcrajt9P3hBE'
    sources:
      better_stack_kubernetes_logs:
        # exclude logs from kube-system namespace
        extra_namespace_label_selector: "kubernetes.io/metadata.name!=kube-system"
      better_stack_kubernetes_metrics_nodes:
        endpoint: 'https://metrics-server.metrics/apis/metrics.k8s.io/v1beta1/nodes'
        tls:
          verify_certificate: False
      better_stack_kubernetes_metrics_pods:
        endpoint: 'https://metrics-server.metrics/apis/metrics.k8s.io/v1beta1/pods'
        tls:
          verify_certificate: False
