apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {ca_cert}
    server: {cluster_endpoint}
  name: {cluster_name}
contexts:
- context:
    cluster: {cluster_name}
    user: {cluster_name}-{user}
  name: {cluster_name}
current-context: {cluster_name}
kind: Config
users:
- name: {cluster_name}-{user}
  user:
    token: {api_token}