apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  labels:
    security: S2
spec:
  containers:
    - name: test-container
      image: python:3.9-slim
      command:
      - sleep
      - '3600'
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - S2
          topologyKey: kubernetes.io/hostname
