apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stay
  template:
    metadata:
      labels:
        app: stay
    spec:
      containers:
      - name: stay
        image: python:3.9-slim
        command:
          - sleep
          - '3600'
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - stay
              topologyKey: "kubernetes.io/hostname"
