apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service1
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - image: logileifs/mockon
        name: helloworld
        args: ['/={"hello": "world"}']
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
          #name: myport
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
  - protocol: TCP
    port: 88
    targetPort: 8080
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: helloworld
#  annotations:
#    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
#    kubernetes.io/ingress.class: azure/application-gateway
#spec:
#  rules:
#  - http:
#      paths:
#      - pathType: Prefix
#        path: /hello/*
#        backend:
#          service:
#            name: service1
#            port:
#              number: 80
#      #- pathType: Prefix
#      #  path: /hello*
#      #  backend:
#      #    service:
#      #      name: service1
#      #      port:
#      #        number: 80
#---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    traefik.ingress.kubernetes.io/router.middlewares: traefik-stripprefix@kubernetescrd
spec:
  rules:
  - http:
#    host: "skelfir-e8ba882f.hcp.northeurope.azmk8s.io"
      paths:
      - backend:
          service:
            name: service1
            port:
              number: 88
        path: /hello
        pathType: ImplementationSpecific
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: service1-ingress
spec:
  routes:
    - match: PathPrefix(`/service1`)
      kind: Rule
      middlewares:
        - name: service1-stripprefix
      services:
        - name: service1
          port: 88
--- 
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: traefik
spec:
  stripPrefix:
    prefixes:
      - /hello
